-- -- Adding new signals subgroups
data:extend({
  {
    type = "item-subgroup",
    name = "kr-special-signals",
    group = "signals",
    order = "z1",
  },
  {
    type = "item-subgroup",
    name = "kr-special-signals-2",
    group = "signals",
    order = "z2",
  },
})

-- -- Adding new signals (virtual signals)
data:extend({
  -- -- WARNINGS
  {
    type = "virtual-signal",
    name = "kr-attention_1",
    icon = "__Krastorio2Assets__/icons/signals/attention_1.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-1[attention_1]",
  },
  {
    type = "virtual-signal",
    name = "kr-attention_2",
    icon = "__Krastorio2Assets__/icons/signals/attention_2.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-2[attention_2]",
  },
  {
    type = "virtual-signal",
    name = "kr-attention_3",
    icon = "__Krastorio2Assets__/icons/signals/attention_3.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-3[attention_3]",
  },
  {
    type = "virtual-signal",
    name = "kr-nuclear-1",
    icon = "__Krastorio2Assets__/icons/signals/nuclear-1.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-4[nuclear-1]",
  },
  {
    type = "virtual-signal",
    name = "kr-nuclear-2",
    icon = "__Krastorio2Assets__/icons/signals/nuclear-2.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-5[nuclear-2]",
  },
  {
    type = "virtual-signal",
    name = "kr-biohazard",
    icon = "__Krastorio2Assets__/icons/signals/biohazard.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-6[biohazard]",
  },
  -- UTILITY
  {
    type = "virtual-signal",
    name = "kr-power",
    icon = "__Krastorio2Assets__/icons/signals/power.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-7[power]",
  },
  {
    type = "virtual-signal",
    name = "kr-power_on",
    icon = "__Krastorio2Assets__/icons/signals/power_on.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-8[power_on]",
  },
  {
    type = "virtual-signal",
    name = "kr-power_off",
    icon = "__Krastorio2Assets__/icons/signals/power_off.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-9[power_off]",
  },
  {
    type = "virtual-signal",
    name = "kr-battery",
    icon = "__Krastorio2Assets__/icons/signals/battery.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-a[battery]",
  },
  {
    type = "virtual-signal",
    name = "kr-battery_low",
    icon = "__Krastorio2Assets__/icons/signals/battery_low.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-b[battery_low]",
  },
  {
    type = "virtual-signal",
    name = "kr-star_w",
    icon = "__Krastorio2Assets__/icons/signals/star_w.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-c[star_w]",
  },
  {
    type = "virtual-signal",
    name = "kr-star_b",
    icon = "__Krastorio2Assets__/icons/signals/star_b.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-d[star_b]",
  },
  {
    type = "virtual-signal",
    name = "kr-energy-1",
    icon = "__Krastorio2Assets__/icons/signals/energy_1.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-e[energy-1]",
  },
  {
    type = "virtual-signal",
    name = "kr-energy-2",
    icon = "__Krastorio2Assets__/icons/signals/energy_2.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-e[energy-2]",
  },
  {
    type = "virtual-signal",
    name = "kr-time",
    icon = "__Krastorio2Assets__/icons/signals/time.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-f[time]",
  },
  {
    type = "virtual-signal",
    name = "kr-gear_w",
    icon = "__Krastorio2Assets__/icons/signals/gear_w.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-g[gear_w]",
  },
  {
    type = "virtual-signal",
    name = "kr-gear_b",
    icon = "__Krastorio2Assets__/icons/signals/gear_b.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-h[gear_b]",
  },
  {
    type = "virtual-signal",
    name = "kr-recycling",
    icon = "__Krastorio2Assets__/icons/signals/recycling.png",
    icon_size = 64,
    subgroup = "kr-special-signals",
    order = "a[special-signals]-i[recycling]",
  },
  {
    type = "virtual-signal",
    name = "kr-build_here",
    icon = "__Krastorio2Assets__/icons/signals/build_here.png",
    icon_size = 64,
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-1[build_here]",
  },
  {
    type = "virtual-signal",
    name = "kr-dont_touch",
    icon = "__Krastorio2Assets__/icons/signals/dont_touch.png",
    icon_size = 64,
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-2[dont_touch]",
  },
  {
    type = "virtual-signal",
    name = "kr-kill",
    icon = "__Krastorio2Assets__/icons/signals/kill.png",
    icon_size = 64,
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-3[kill]",
  },
  {
    type = "virtual-signal",
    name = "kr-wtf",
    icon = "__Krastorio2Assets__/icons/signals/wtf.png",
    icon_size = 64,
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-4[wtf]",
  },
  {
    type = "virtual-signal",
    name = "kr-heart",
    icon = "__Krastorio2Assets__/icons/signals/heart.png",
    icon_size = 64,
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-5[heart]",
  },
  {
    type = "virtual-signal",
    name = "kr-smile",
    icon = "__Krastorio2Assets__/icons/signals/smile.png",
    icon_size = 64,
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-zz9[smile]",
  },
  {
    type = "virtual-signal",
    name = "kr-scull",
    icon = "__Krastorio2Assets__/icons/signals/scull.png",
    icon_size = 64,
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-zz9[scull]",
  },
  {
    type = "virtual-signal",
    name = "kr-krastorio",
    icon = "__Krastorio2Assets__/icons/signals/krastorio.png",
    icon_size = 64,
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-zzz[krastorio]",
  },
  {
    type = "virtual-signal",
    name = "kr-question-mark",
    icon = "__Krastorio2Assets__/icons/signals/question-mark.png",
    icon_size = 64,
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-www[question-mark]",
  },
})
