kr_optimization_tech_card_name = "space-science-pack"
require("prototypes.compatibility.space-exploration-pre")

require("prototypes.achievements")
require("prototypes.custom-inputs")
require("prototypes.damage-types")
require("prototypes.equipment-grids")
require("prototypes.fluids")
require("prototypes.gui-styles")
require("prototypes.shortcuts")
require("prototypes.sounds")
require("prototypes.tips-and-tricks")
require("prototypes.virtual-signals")

require("prototypes.armors.power-armor-mk3")
require("prototypes.armors.power-armor-mk4")

require("prototypes.categories.ammo-categories")
require("prototypes.categories.equipment-categories")
require("prototypes.categories.fuel-categories")
require("prototypes.categories.item-subgroups")
require("prototypes.categories.recipe-categories")
require("prototypes.categories.resource-categories")

require("prototypes.entities.advanced-assembling-machine")
require("prototypes.entities.advanced-chemical-plant")
require("prototypes.entities.advanced-furnace")
require("prototypes.entities.advanced-loader")
require("prototypes.entities.advanced-solar-panel")
require("prototypes.entities.advanced-splitter")
require("prototypes.entities.advanced-steam-turbine")
require("prototypes.entities.advanced-transport-belt")
require("prototypes.entities.advanced-underground-belt")
require("prototypes.entities.air-purifier")
require("prototypes.entities.antimatter-reactor")
require("prototypes.entities.atmospheric-condenser")
require("prototypes.entities.big-active-provider-container")
require("prototypes.entities.big-buffer-container")
require("prototypes.entities.big-container")
require("prototypes.entities.big-passive-provider-container")
require("prototypes.entities.big-requester-container")
require("prototypes.entities.big-storage-container")
require("prototypes.entities.bio-lab")
require("prototypes.entities.biusart-lab")
require("prototypes.entities.crash-site-assembling-machine-1")
require("prototypes.entities.crash-site-assembling-machine-2")
require("prototypes.entities.crash-site-generator")
require("prototypes.entities.crash-site-lab")
require("prototypes.entities.crusher")
require("prototypes.entities.electric-mining-drill-mk2")
require("prototypes.entities.electric-mining-drill-mk3")
require("prototypes.entities.electrolysis-plant")
require("prototypes.entities.energy-storage")
require("prototypes.entities.express-loader")
require("prototypes.entities.fast-loader")
require("prototypes.entities.filtration-plant")
require("prototypes.entities.flare-stack")
require("prototypes.entities.fluid-storage-1")
require("prototypes.entities.fluid-storage-2")
require("prototypes.entities.fuel-refinery")
require("prototypes.entities.fusion-reactor")
require("prototypes.entities.gas-power-station")
require("prototypes.entities.greenhouse")
require("prototypes.entities.intergalactic-transceiver")
require("prototypes.entities.large-roboport")
require("prototypes.entities.laser-artillery-turret")
require("prototypes.entities.loader")
require("prototypes.entities.logo")
require("prototypes.entities.matter-assembler")
require("prototypes.entities.matter-plant")
require("prototypes.entities.medium-active-provider-container")
require("prototypes.entities.medium-buffer-container")
require("prototypes.entities.medium-container")
require("prototypes.entities.medium-passive-provider-container")
require("prototypes.entities.medium-requester-container")
require("prototypes.entities.medium-storage-container")
require("prototypes.entities.mineral-water-pumpjack")
require("prototypes.entities.planetary-teleporter")
require("prototypes.entities.quantum-computer")
require("prototypes.entities.quarry-drill")
require("prototypes.entities.railgun-turret")
require("prototypes.entities.research-server")
require("prototypes.entities.rocket-turret")
require("prototypes.entities.sentinel")
require("prototypes.entities.shelter")
require("prototypes.entities.shelter-plus")
require("prototypes.entities.singularity-beacon")
require("prototypes.entities.singularity-lab")
require("prototypes.entities.small-roboport")
require("prototypes.entities.stabilizer-charging-station")
require("prototypes.entities.steel-pipe")
require("prototypes.entities.steel-pipe-to-ground")
require("prototypes.entities.steel-pump")
require("prototypes.entities.superior-inserter")
require("prototypes.entities.superior-loader")
require("prototypes.entities.superior-long-inserter")
require("prototypes.entities.superior-splitter")
require("prototypes.entities.superior-substation")
require("prototypes.entities.superior-transport-belt")
require("prototypes.entities.superior-underground-belt")
require("prototypes.entities.tesla-coil")
require("prototypes.entities.wind-turbine")

require("prototypes.equipment.additional-engine-equipment")
require("prototypes.equipment.advanced-additional-engine-equipment")
require("prototypes.equipment.advanced-exoskeleton-equipment")
require("prototypes.equipment.antimatter-reactor-equipment")
require("prototypes.equipment.battery-mk3-equipment")
require("prototypes.equipment.big-battery-equipment")
require("prototypes.equipment.big-battery-mk2-equipment")
require("prototypes.equipment.big-battery-mk3-equipment")
require("prototypes.equipment.big-solar-panel-equipment")
require("prototypes.equipment.big-superior-solar-panel-equipment")
require("prototypes.equipment.cyber-potato-equipment")
require("prototypes.equipment.energy-absorber-equipment")
require("prototypes.equipment.energy-shield-mk3-equipment")
require("prototypes.equipment.energy-shield-mk4-equipment")
require("prototypes.equipment.nuclear-reactor-equipment")
require("prototypes.equipment.personal-laser-defense-mk2-equipment")
require("prototypes.equipment.personal-laser-defense-mk3-equipment")
require("prototypes.equipment.personal-laser-defense-mk4-equipment")
require("prototypes.equipment.personal-submachine-laser-defense-mk1-equipment")
require("prototypes.equipment.personal-submachine-laser-defense-mk2-equipment")
require("prototypes.equipment.personal-submachine-laser-defense-mk3-equipment")
require("prototypes.equipment.personal-submachine-laser-defense-mk4-equipment")
require("prototypes.equipment.portable-generator-equipment")
require("prototypes.equipment.small-portable-generator-equipment")
require("prototypes.equipment.superior-exoskeleton-equipment")
require("prototypes.equipment.superior-night-vision-equipment")
require("prototypes.equipment.superior-solar-panel-equipment")
require("prototypes.equipment.vehicle-roboport-equipment")

require("prototypes.explosions.beacon-matter-explosion")
require("prototypes.explosions.impulse-rifle-beam")
require("prototypes.explosions.kr-laser-explosion")
require("prototypes.explosions.kr-laser-explosion-gunshot")
require("prototypes.explosions.kr-laser-explosion-gunshot-smoke-fast")
require("prototypes.explosions.matter-explosion")
require("prototypes.explosions.matter-explosion-s")
require("prototypes.explosions.matter-fire-smoke")
require("prototypes.explosions.matter-shockwave")
require("prototypes.explosions.medium-matter-explosion")
require("prototypes.explosions.rail-matter-explosion")
require("prototypes.explosions.small-matter-explosion")

require("prototypes.projectiles.antimatter-artillery-projectile")
require("prototypes.projectiles.antimatter-bomb-wave")
require("prototypes.projectiles.antimatter-bomb-wave-spawns-fire-smoke-explosion")
require("prototypes.projectiles.antimatter-bomb-wave-spawns-matter-shockwave-explosion")
require("prototypes.projectiles.antimatter-bomb-wave-spawns-matter-smoke")
require("prototypes.projectiles.antimatter-rocket-projectile")
require("prototypes.projectiles.atomic-artillery")
require("prototypes.projectiles.basic-railgun-projectile")
require("prototypes.projectiles.beacon-wave")
require("prototypes.projectiles.explosion-railgun-projectile")
require("prototypes.projectiles.explosion-turret-rocket-projectile")
require("prototypes.projectiles.heavy-explosive-rocket-projectile")
require("prototypes.projectiles.intergalactic-transceiver-wave")
require("prototypes.projectiles.laser-projectile")
require("prototypes.projectiles.matter-railgun-projectile")
require("prototypes.projectiles.matter-turret-rocket-projectile")
require("prototypes.projectiles.matter-wave")
require("prototypes.projectiles.nuclear-turret-rocket-projectile")
require("prototypes.projectiles.poop-projectile")
require("prototypes.projectiles.virus-capsule")
require("prototypes.projectiles.virus-capsule-metal-particle")

require("prototypes.remnants.advanced-splitter-remnant")
require("prototypes.remnants.advanced-tank-remnant")
require("prototypes.remnants.advanced-transport-belt-remnant")
require("prototypes.remnants.advanced-underground-belt-remnant")
require("prototypes.remnants.antimatter-reactor-remnant")
require("prototypes.remnants.fusion-reactor-remnant")
require("prototypes.remnants.kr-big-random-pipes-remnant")
require("prototypes.remnants.kr-medium-random-pipes-remnant")
require("prototypes.remnants.kr-mineral-water-pumpjack-remnant")
require("prototypes.remnants.matter-plant-remnant")
require("prototypes.remnants.superior-inserter-remnant")
require("prototypes.remnants.superior-splitter-remnant")
require("prototypes.remnants.superior-transport-belt-remnant")
require("prototypes.remnants.superior-underground-belt-remnant")
require("prototypes.remnants.turret-remnant")

require("prototypes.smokes.matter-smoke")
require("prototypes.smokes.poison-capsule-particle-smoke")
require("prototypes.smokes.poop-cloud")
require("prototypes.smokes.poop-cloud-visual-dummy")
require("prototypes.smokes.poop-particle-smoke")
require("prototypes.smokes.virus-cloud")
require("prototypes.smokes.virus-cloud-visual-dummy")
require("prototypes.smokes.virus-particle-smoke")

require("prototypes.vehicles.advanced-tank")
require("prototypes.vehicles.nuclear-locomotive")

---------------------------------------------------------------------------
-- -- -- PRE INITIALIZATION
---------------------------------------------------------------------------
-- -- General Info
krastorio = {}
-- -- Global Krastorio 2 library initialization, utilities library (support for main library)
require("lib.private.data-stages.utils.krastorio_utils")
-- -- Global Krastorio 2 library initialization, Krastorio 2 main library
require("lib.private.data-stages.entities")
require("lib.private.data-stages.equipments")
require("lib.private.data-stages.general")
require("lib.private.data-stages.icons")
require("lib.private.data-stages.items")
require("lib.private.data-stages.modules")
require("lib.private.data-stages.recipes")
require("lib.private.data-stages.technologies")

---------------------------------------------------------------------------
-- -- -- CONTENTS INITIALIZATION (data stage)
---------------------------------------------------------------------------
-- -- Adding new items
require("prototypes.items.items-initialization")
-- -- Adding new particles
require("prototypes.particles.particles-initialization")
-- -- Adding new recipes
require("prototypes.recipes.recipes-initialization")
-- -- Adding new resources
require("prototypes.resources.resources-initialization")
-- -- Adding new sounds (prototypes)
-- -- Adding new technologies
require("prototypes.technologies.technologies-initialization")
-- -- Adding new tiles
require("prototypes.tiles.tiles-initialization")
-- -- Adding new signals (virtual signals)
-- -- Adding new key binds
---------------------------------------------------------------------------
-- -- -- OPTIONAL CONTENTS INITIALIZATION (data stage)
---------------------------------------------------------------------------

---------------------------------------------------------------------------
-- -- -- COMPATIBILITY INITIALIZATION (data stage)
---------------------------------------------------------------------------
-- -- Execute Compatilbility Scripts for the data stage
require("compatibility-scripts.data.aircraft")
require("compatibility-scripts.data.early-electric-furnaces")
require("compatibility-scripts.data.deadlock-beltboxes-loaders")
require("compatibility-scripts.data.IndustrialRevolution")
require("compatibility-scripts.data.Squeak_Through")
---------------------------------------------------------------------------
