kr_optimization_tech_card_name = "space-science-pack"
require("prototypes.compatibility.space-exploration-pre")

require("prototypes.achievements")
require("prototypes.damage-type")
require("prototypes.item-groups")

require("prototypes.categories.ammo-category")
require("prototypes.categories.equipment-category")
require("prototypes.categories.fuel-category")
require("prototypes.categories.recipe-category")
require("prototypes.categories.resource-category")

-- Library - to be deprecated
krastorio = {}
require("lib.private.data-stages.utils.krastorio_utils")
require("lib.private.data-stages.entities")
require("lib.private.data-stages.equipments")
require("lib.private.data-stages.general")
require("lib.private.data-stages.icons")
require("lib.private.data-stages.items")
require("lib.private.data-stages.modules")
require("lib.private.data-stages.recipes")
require("lib.private.data-stages.technologies")

require("prototypes.entities.entities-initialization")
require("prototypes.equipments.equipments-initialization")
require("prototypes.fluids.fluids-initialization")
require("prototypes.gui.gui-initialization")
require("prototypes.gui.tips-and-tricks-initialization")
require("prototypes.items.items-initialization")
require("prototypes.particles.particles-initialization")
require("prototypes.recipes.recipes-initialization")
require("prototypes.resources.resources-initialization")
require("prototypes.sounds.sounds")
require("prototypes.technologies.technologies-initialization")
require("prototypes.tiles.tiles-initialization")
require("prototypes.others.virtual-signals-initialization")
require("prototypes.others.key-bind-initialization")
require("prototypes.others.shortcut")

require("compatibility-scripts.data.aircraft")
require("compatibility-scripts.data.early-electric-furnaces")
require("compatibility-scripts.data.deadlock-beltboxes-loaders")
require("compatibility-scripts.data.Squeak_Through")
