require("prototypes.updates.base.achievements")
require("prototypes.updates.base.ammo")
require("prototypes.updates.base.autoplace-controls")
require("prototypes.updates.base.entities")
require("prototypes.updates.base.equipment-grids")
require("prototypes.updates.base.equipment")
require("prototypes.updates.base.fluids")
require("prototypes.updates.base.guns")
require("prototypes.updates.base.items")
require("prototypes.updates.base.main-menu")
require("prototypes.updates.base.projectiles")
require("prototypes.updates.base.recipes")
require("prototypes.updates.base.resources")
require("prototypes.updates.base.technologies")
require("prototypes.updates.base.turrets")
require("prototypes.updates.base.weapons-realistic")
require("prototypes.updates.base.weapons-standard")

require("prototypes.updates.add-automation-core-recipes")
require("prototypes.updates.add-basic-tech-card")
require("prototypes.updates.adjust-spawn-rates")
require("prototypes.updates.adjust-stack-sizes")
require("prototypes.updates.convert-furnaces-to-assemblers")
require("prototypes.updates.enable-burner-leech")
require("prototypes.updates.finite-oil")
require("prototypes.updates.generate-flare-stack-recipes")
require("prototypes.updates.generate-greenhouse-recipes")
require("prototypes.updates.generate-matter-recipes")
require("prototypes.updates.generate-roboport-variations")
require("prototypes.updates.generate-void-crushing-recipes")
require("prototypes.updates.remove-nuclear-fuel")
require("prototypes.updates.set-new-resource-autoplace")

-- Has to be after base updates so it can use the updated icons
require("prototypes.recipes.smelting-crafting")
