require("prototypes.entities.advanced-belt-animation-set") -- Must be loaded before the belts set
require("prototypes.entities.advanced-splitter")
require("prototypes.entities.advanced-transport-belt")
require("prototypes.entities.advanced-underground-belt")
require("prototypes.entities.superior-belt-animation-set") -- Must be loaded before the belts set
require("prototypes.entities.superior-splitter")
require("prototypes.entities.superior-transport-belt")
require("prototypes.entities.superior-underground-belt")
require("prototypes.entities.loaders") -- Must be required after belts
require("prototypes.entities.remnants.advanced-tank-remnant")
require("prototypes.entities.remnants.fusion-reactor-remnant")
require("prototypes.entities.remnants.antimatter-reactor-remnant")
require("prototypes.entities.remnants.kr-big-random-pipes-remnant")
require("prototypes.entities.remnants.kr-medium-random-pipes-remnant")
require("prototypes.entities.remnants.kr-mineral-water-pumpjack-remnant")
require("prototypes.entities.remnants.matter-plant-remnant")
require("prototypes.entities.remnants.superior-inserter-remnant")
require("prototypes.entities.remnants.turret-remnant")
require("prototypes.entities.remnants.advanced-splitter-remnant")
require("prototypes.entities.remnants.advanced-transport-belt-remnant")
require("prototypes.entities.remnants.advanced-underground-belt-remnant")
require("prototypes.entities.remnants.superior-splitter-remnant")
require("prototypes.entities.remnants.superior-transport-belt-remnant")
require("prototypes.entities.remnants.superior-underground-belt-remnant")
require("prototypes.entities.advanced-tank")
require("prototypes.entities.nuclear-locomotive")
require("prototypes.entities.explosions")
require("prototypes.entities.projectiles")
