data:extend({
  {
    type = "technology",
    name = "kr-advanced-pickaxe",
    mod = "Krastorio2",
    icon_size = 256,
    icon_mipmaps = 4,
    icons = {
      {
        icon = "__Krastorio2Assets__/technologies/imersium-pickaxe.png",
        icon_size = 256,
        icon_mipmaps = 4,
      },
      {
        icon = "__core__/graphics/icons/technology/constants/constant-mining.png",
        icon_size = 128,
        icon_mipmaps = 3,
        shift = { 100, 100 },
      },
    },
    effects = {
      {
        type = "character-mining-speed",
        modifier = 2,
      },
    },
    prerequisites = { "steel-axe", "kr-imersium-processing" },
    unit = {
      count = 200,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "advanced-tech-card", 1 },
        { "matter-tech-card", 1 },
      },
      time = 60,
    },
  },
  {
    type = "technology",
    name = "kr-advanced-tech-card",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/advanced-tech-card.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {
      {
        type = "unlock-recipe",
        recipe = "advanced-tech-card",
      },
    },
    prerequisites = { "kr-imersium-processing" },
    unit = {
      count = 1000,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-energy-control-unit",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/energy-control-unit.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {
      {
        type = "unlock-recipe",
        recipe = "energy-control-unit",
      },
    },
    prerequisites = { "kr-singularity-lab", "kr-lithium-sulfur-battery", "kr-matter-tech-card" },
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 30,
    },
  },
  {
    type = "technology",
    name = "kr-energy-storage",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/energy-storage.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {
      {
        type = "unlock-recipe",
        recipe = "kr-energy-storage",
      },
    },
    prerequisites = { "electric-energy-accumulators", "kr-matter-tech-card", "kr-energy-control-unit" },
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-imersium-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/imersium-processing.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {
      {
        type = "unlock-recipe",
        recipe = "imersium-plate",
      },
      {
        type = "unlock-recipe",
        recipe = "imersium-gear-wheel",
      },
      {
        type = "unlock-recipe",
        recipe = "imersium-beam",
      },
    },
    prerequisites = { "kr-matter-tech-card" },
    unit = {
      count = 500,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 60,
    },
  },
  {
    type = "technology",
    name = "kr-improved-pollution-filter",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/improved-pollution-filter.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {
      {
        type = "unlock-recipe",
        recipe = "improved-pollution-filter",
      },
      {
        type = "unlock-recipe",
        recipe = "kr-air-cleaning-2",
      },
      {
        type = "unlock-recipe",
        recipe = "restore-used-improved-pollution-filter",
      },
    },
    prerequisites = { "kr-matter-tech-card", "kr-air-purification" },
    unit = {
      count = 200,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 30,
    },
  },
  {
    type = "technology",
    name = "kr-matter-coal-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-coal.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-coal-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-coal.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-copper-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-copper.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-copper-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-copper.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-iron-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-iron.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-iron-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-iron.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-minerals-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-minerals.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-minerals-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-minerals.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-oil-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-oil.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-oil-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-oil.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-processing.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {
      {
        type = "unlock-recipe",
        recipe = "kr-matter-plant",
      },
      {
        type = "unlock-recipe",
        recipe = "kr-matter-associator",
      },
      {
        type = "unlock-recipe",
        recipe = "kr-stabilizer-charging-station",
      },
      {
        type = "unlock-recipe",
        recipe = "matter-stabilizer",
      },
      {
        type = "unlock-recipe",
        recipe = "charge-stabilizer",
      },
    },
    prerequisites = { "kr-matter-tech-card", "kr-imersium-processing", "kr-energy-control-unit" },
    order = "g-e-d",
    unit = {
      count = 1000,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-processing.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {
      {
        type = "unlock-recipe",
        recipe = "kr-matter-plant",
      },
      {
        type = "unlock-recipe",
        recipe = "kr-matter-associator",
      },
      {
        type = "unlock-recipe",
        recipe = "kr-stabilizer-charging-station",
      },
      {
        type = "unlock-recipe",
        recipe = "matter-stabilizer",
      },
      {
        type = "unlock-recipe",
        recipe = "charge-stabilizer",
      },
    },
    prerequisites = { "kr-matter-tech-card", "kr-imersium-processing", "kr-energy-control-unit" },
    order = "g-e-d",
    unit = {
      count = 1000,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-rare-metals-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-rare-metals.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-rare-metals-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-rare-metals.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-stone-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-stone.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-stone-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-stone.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-uranium-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-uranium.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-uranium-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-uranium.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-water-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-water.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-matter-water-processing",
    mod = "Krastorio2",
    icon = "__Krastorio2Assets__/technologies/matter-water.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {},
    prerequisites = { "kr-matter-processing" },
    order = "g-e-e",
    unit = {
      count = 350,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
  {
    type = "technology",
    name = "kr-robot-battery-plus",
    icon = "__Krastorio2Assets__/technologies/robot-battery-plus.png",
    icon_size = 256,
    icon_mipmaps = 4,
    effects = {
      {
        type = "worker-robot-battery",
        modifier = 0.6,
      },
    },
    prerequisites = { "kr-robot-battery", "kr-advanced-roboports", "kr-energy-control-unit" },
    unit = {
      count = 1000,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
        { kr_optimization_tech_card_name, 1 },
        { "matter-tech-card", 1 },
      },
      time = 45,
    },
  },
})
