return {
  -----------------------------------------------------------------------------------------------------------------
  -----------------------------------------------------------------------------------------------------------------
  -----------------------------------------------------------------------------------------------------------------
  {
    type = "recipe",
    name = "kr-greenhouse",
    energy_required = 10,
    enabled = false,
    ingredients = {
      { type = "item", name = "wood", amount = 20 },
      { type = "item", name = "iron-beam", amount = 10 },
      { type = "item", name = "glass", amount = 20 },
      { type = "item", name = "automation-core", amount = 2 },
    },
    results = { { type = "item", name = "kr-greenhouse", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-electric-mining-drill-mk2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "electric-mining-drill", amount = 1 },
      { type = "item", name = "steel-gear-wheel", amount = 5 },
      { type = "item", name = "rare-metals", amount = 4 },
    },
    results = { { type = "item", name = "kr-electric-mining-drill-mk2", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-electric-mining-drill-mk3",
    energy_required = 10,
    enabled = false,
    ingredients = {
      { type = "item", name = "kr-electric-mining-drill-mk2", amount = 1 },
      { type = "item", name = "imersium-gear-wheel", amount = 5 },
      { type = "item", name = "imersite-crystal", amount = 4 },
    },
    results = { { type = "item", name = "kr-electric-mining-drill-mk3", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-shelter",
    energy_required = 10,
    enabled = false,
    ingredients = {
      { type = "item", name = "iron-beam", amount = 25 },
      { type = "item", name = "iron-plate", amount = 25 },
      { type = "item", name = "copper-cable", amount = 10 },
      { type = "item", name = "coal", amount = 50 },
    },
    results = { { type = "item", name = "kr-shelter", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-mineral-water-pumpjack",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "automation-core", amount = 2 },
      { type = "item", name = "steel-gear-wheel", amount = 5 },
      { type = "item", name = "steel-beam", amount = 5 },
      { type = "item", name = "pipe", amount = 5 },
    },
    results = { { type = "item", name = "kr-mineral-water-pumpjack", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-sentinel",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "glass", amount = 1 },
      { type = "item", name = "iron-plate", amount = 2 },
      { type = "item", name = "copper-cable", amount = 1 },
      { type = "item", name = "automation-core", amount = 1 },
    },
    results = { { type = "item", name = "kr-sentinel", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-gas-power-station",
    energy_required = 10,
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-beam", amount = 10 },
      { type = "item", name = "engine-unit", amount = 20 },
      { type = "item", name = "electronic-circuit", amount = 4 },
      { type = "item", name = "pipe", amount = 4 },
    },
    results = { { type = "item", name = "kr-gas-power-station", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-tesla-coil",
    energy_required = 20,
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-beam", amount = 20 },
      { type = "item", name = "electronic-circuit", amount = 20 },
      { type = "item", name = "copper-cable", amount = 100 },
    },
    results = { { type = "item", name = "kr-tesla-coil", amount = 1 } },
  },
  -- -- --
  -- NEW LABORATORIES
  -- -- --
  {
    type = "recipe",
    name = "biusart-lab",
    energy_required = 10,
    enabled = false,
    ingredients = {
      { type = "item", name = "advanced-circuit", amount = 10 },
      { type = "item", name = "steel-beam", amount = 5 },
      { type = "item", name = "lab", amount = 1 },
      { type = "item", name = "copper-cable", amount = 10 },
    },
    results = { { type = "item", name = "biusart-lab", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-singularity-lab",
    energy_required = 120,
    enabled = false,
    ingredients = {
      { type = "item", name = "ai-core", amount = 20 },
      { type = "item", name = "biusart-lab", amount = 5 },
      { type = "item", name = "steel-plate", amount = 40 },
      { type = "item", name = "electric-engine-unit", amount = 30 },
      { type = "item", name = "rare-metals", amount = 60 },
      { type = "item", name = "processing-unit", amount = 100 },
    },
    results = { { type = "item", name = "kr-singularity-lab", amount = 1 } },
  },
  -- -- --
  -- Research servers
  -- -- --
  {
    type = "recipe",
    name = "kr-research-server",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-beam", amount = 4 },
      { type = "item", name = "advanced-circuit", amount = 5 },
      { type = "item", name = "electronic-components", amount = 50 },
    },
    results = { { type = "item", name = "kr-research-server", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-quantum-computer",
    energy_required = 120,
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-beam", amount = 20 },
      { type = "item", name = "copper-plate", amount = 20 },
      { type = "item", name = "rare-metals", amount = 50 },
      { type = "item", name = "ai-core", amount = 50 },
      { type = "item", name = "electronic-components", amount = 100 },
      { type = "item", name = "processing-unit", amount = 100 },
    },
    results = { { type = "item", name = "kr-quantum-computer", amount = 1 } },
  },
  -- -- --
  -- FLUID STORAGES
  -- -- --
  {
    type = "recipe",
    name = "kr-fluid-storage-1",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-beam", amount = 10 },
      { type = "item", name = "steel-plate", amount = 20 },
      { type = "item", name = "kr-steel-pipe", amount = 4 },
    },
    results = { { type = "item", name = "kr-fluid-storage-1", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-fluid-storage-2",
    energy_required = 10,
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-beam", amount = 20 },
      { type = "item", name = "steel-plate", amount = 60 },
      { type = "item", name = "kr-steel-pipe", amount = 12 },
    },
    results = { { type = "item", name = "kr-fluid-storage-2", amount = 1 } },
  },
  -- -- --
  {
    type = "recipe",
    name = "kr-steel-pipe",
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-plate", amount = 1 },
    },
    results = { { type = "item", name = "kr-steel-pipe", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-steel-pipe-to-ground",
    enabled = false,
    ingredients = {
      { type = "item", name = "kr-steel-pipe", amount = 15 },
      { type = "item", name = "steel-plate", amount = 5 },
    },
    results = { { type = "item", name = "kr-steel-pipe-to-ground", amount = 2 } },
  },
  {
    type = "recipe",
    name = "kr-steel-pump",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-gear-wheel", amount = 4 },
      { type = "item", name = "engine-unit", amount = 1 },
      { type = "item", name = "steel-beam", amount = 1 },
      { type = "item", name = "kr-steel-pipe", amount = 1 },
    },
    results = { { type = "item", name = "kr-steel-pump", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-quarry-drill",
    energy_required = 60,
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-beam", amount = 50 },
      { type = "item", name = "steel-plate", amount = 50 },
      { type = "item", name = "rare-metals", amount = 50 },
      { type = "item", name = "electric-engine-unit", amount = 100 },
      { type = "item", name = "processing-unit", amount = 20 },
    },
    results = { { type = "item", name = "kr-quarry-drill", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-matter-plant",
    energy_required = 30,
    enabled = false,
    ingredients = {
      { type = "item", name = "imersium-beam", amount = 10 },
      { type = "item", name = "kr-steel-pipe", amount = 10 },
      { type = "item", name = "energy-control-unit", amount = 10 },
      { type = "item", name = "ai-core", amount = 5 },
    },
    results = { { type = "item", name = "kr-matter-plant", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-matter-assembler",
    energy_required = 30,
    enabled = false,
    ingredients = {
      { type = "item", name = "imersium-beam", amount = 4 },
      { type = "item", name = "kr-steel-pipe", amount = 4 },
      { type = "item", name = "energy-control-unit", amount = 10 },
      { type = "item", name = "ai-core", amount = 3 },
    },
    results = { { type = "item", name = "kr-matter-assembler", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-stabilizer-charging-station",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "imersium-beam", amount = 4 },
      { type = "item", name = "energy-control-unit", amount = 20 },
      { type = "item", name = "processing-unit", amount = 1 },
    },
    results = { { type = "item", name = "kr-stabilizer-charging-station", amount = 1 } },
  },
  ---
  -- Belts
  ---
  -- Advanced
  {
    type = "recipe",
    name = "kr-advanced-splitter",
    --category = "crafting-with-fluid",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "express-splitter", amount = 1 },
      { type = "item", name = "steel-gear-wheel", amount = 4 },
      { type = "item", name = "advanced-circuit", amount = 1 },
    },
    results = { { type = "item", name = "kr-advanced-splitter", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-advanced-transport-belt",
    --category = "crafting-with-fluid",
    energy_required = 0.5,
    enabled = false,
    ingredients = {
      { type = "item", name = "express-transport-belt", amount = 1 },
      { type = "item", name = "steel-gear-wheel", amount = 4 },
      { type = "item", name = "rare-metals", amount = 1 },
    },
    results = { { type = "item", name = "kr-advanced-transport-belt", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-advanced-underground-belt",
    --category = "crafting-with-fluid",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "express-underground-belt", amount = 2 },
      { type = "item", name = "kr-advanced-transport-belt", amount = 30 },
    },
    results = { { type = "item", name = "kr-advanced-underground-belt", amount = 2 } },
  },
  -- Superior
  {
    type = "recipe",
    name = "kr-superior-splitter",
    --category = "crafting-with-fluid",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "kr-advanced-splitter", amount = 1 },
      { type = "item", name = "imersium-gear-wheel", amount = 4 },
      { type = "item", name = "processing-unit", amount = 1 },
    },
    results = { { type = "item", name = "kr-superior-splitter", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-superior-transport-belt",
    --category = "crafting-with-fluid",
    energy_required = 0.5,
    enabled = false,
    ingredients = {
      { type = "item", name = "kr-advanced-transport-belt", amount = 1 },
      { type = "item", name = "imersium-gear-wheel", amount = 4 },
      { type = "item", name = "low-density-structure", amount = 1 },
    },
    results = { { type = "item", name = "kr-superior-transport-belt", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-superior-underground-belt",
    --category = "crafting-with-fluid",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "kr-advanced-underground-belt", amount = 2 },
      { type = "item", name = "kr-superior-transport-belt", amount = 40 },
    },
    results = { { type = "item", name = "kr-superior-underground-belt", amount = 2 } },
  },
  -- -- --
  -- Superior inserters
  -- -- --
  {
    type = "recipe",
    name = "kr-superior-inserter",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "inserter-parts", amount = 1 },
      { type = "item", name = "imersium-plate", amount = 1 },
      { type = "item", name = "imersium-gear-wheel", amount = 4 },
      { type = "item", name = "processing-unit", amount = 1 },
    },
    results = { { type = "item", name = "kr-superior-inserter", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-superior-long-inserter",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "inserter-parts", amount = 2 },
      { type = "item", name = "imersium-plate", amount = 2 },
      { type = "item", name = "imersium-gear-wheel", amount = 4 },
      { type = "item", name = "processing-unit", amount = 1 },
    },
    results = { { type = "item", name = "kr-superior-long-inserter", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-superior-filter-inserter",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "inserter-parts", amount = 1 },
      { type = "item", name = "imersium-plate", amount = 1 },
      { type = "item", name = "imersium-gear-wheel", amount = 4 },
      { type = "item", name = "processing-unit", amount = 2 },
    },
    results = { { type = "item", name = "kr-superior-filter-inserter", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-superior-long-filter-inserter",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "inserter-parts", amount = 2 },
      { type = "item", name = "imersium-plate", amount = 2 },
      { type = "item", name = "imersium-gear-wheel", amount = 4 },
      { type = "item", name = "processing-unit", amount = 2 },
    },
    results = { { type = "item", name = "kr-superior-long-filter-inserter", amount = 1 } },
  },
  -- -- --
  {
    type = "recipe",
    name = "kr-advanced-assembling-machine",
    energy_required = 10,
    enabled = false,
    ingredients = {
      { type = "item", name = "imersium-beam", amount = 4 },
      { type = "item", name = "assembling-machine-3", amount = 2 },
      { type = "item", name = "electric-furnace", amount = 2 },
      { type = "item", name = "ai-core", amount = 2 },
    },
    results = { { type = "item", name = "kr-advanced-assembling-machine", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-large-roboport",
    energy_required = 30,
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-plate", amount = 20 },
      { type = "item", name = "imersium-beam", amount = 20 },
      { type = "item", name = "imersium-gear-wheel", amount = 20 },
      { type = "item", name = "rare-metals", amount = 80 },
      { type = "item", name = "ai-core", amount = 10 },
      { type = "item", name = "roboport", amount = 1 },
    },
    results = { { type = "item", name = "kr-large-roboport", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-small-roboport",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "imersium-beam", amount = 3 },
      { type = "item", name = "steel-plate", amount = 10 },
      { type = "item", name = "rare-metals", amount = 20 },
      { type = "item", name = "ai-core", amount = 1 },
      { type = "item", name = "electronic-components", amount = 5 },
    },
    results = { { type = "item", name = "kr-small-roboport", amount = 2 } },
  },
  {
    type = "recipe",
    name = "kr-singularity-beacon",
    energy_required = 10,
    enabled = false,
    ingredients = {
      { type = "item", name = "beacon", amount = 1 },
      { type = "item", name = "ai-core", amount = 10 },
      { type = "item", name = "processing-unit", amount = 20 },
      { type = "item", name = "energy-control-unit", amount = 10 },
    },
    results = { { type = "item", name = "kr-singularity-beacon", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-railgun-turret",
    enabled = false,
    energy_required = 20,
    ingredients = {
      { type = "item", name = "gun-turret", amount = 4 },
      { type = "item", name = "steel-beam", amount = 10 },
      { type = "item", name = "processing-unit", amount = 10 },
      { type = "item", name = "rare-metals", amount = 20 },
      { type = "item", name = "low-density-structure", amount = 10 },
    },
    results = { { type = "item", name = "kr-railgun-turret", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-rocket-turret",
    enabled = false,
    energy_required = 20,
    ingredients = {
      { type = "item", name = "rocket-launcher", amount = 6 },
      { type = "item", name = "steel-beam", amount = 10 },
      { type = "item", name = "rare-metals", amount = 20 },
      { type = "item", name = "processing-unit", amount = 20 },
      { type = "item", name = "low-density-structure", amount = 10 },
    },
    results = { { type = "item", name = "kr-rocket-turret", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-laser-artillery-turret",
    enabled = false,
    energy_required = 20,
    ingredients = {
      { type = "item", name = "energy-control-unit", amount = 6 },
      { type = "item", name = "steel-beam", amount = 10 },
      { type = "item", name = "rare-metals", amount = 20 },
      { type = "item", name = "ai-core", amount = 10 },
      { type = "item", name = "low-density-structure", amount = 10 },
    },
    results = { { type = "item", name = "kr-laser-artillery-turret", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-planetary-teleporter",
    energy_required = 20,
    enabled = false,
    ingredients = {
      { type = "item", name = "imersium-beam", amount = 10 },
      { type = "item", name = "imersite-crystal", amount = 4 },
      { type = "item", name = "energy-control-unit", amount = 8 },
      { type = "item", name = "teleportation-gps-module", amount = 1 },
    },
    results = { { type = "item", name = "kr-planetary-teleporter", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-intergalactic-transceiver",
    energy_required = 600,
    enabled = false,
    ingredients = {
      { type = "item", name = "imersium-beam", amount = 500 },
      { type = "item", name = "imersium-plate", amount = 500 },
      { type = "item", name = "rare-metals", amount = 1000 },
      { type = "item", name = "energy-control-unit", amount = 500 },
      { type = "item", name = "ai-core", amount = 300 },
      { type = "item", name = "concrete", amount = 750 },
    },
    results = { { type = "item", name = "kr-intergalactic-transceiver", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-logo",
    energy_required = 666,
    enabled = false,
    ingredients = {
      { type = "item", name = "iron-stick", amount = 5000 },
      { type = "item", name = "poop", amount = 1 },
    },
    results = { { type = "item", name = "kr-logo", amount = 1 } },
  },
  -----------------------------------------------------------------------------------------------------------------
  -----------------------------------------------------------------------------------------------------------------
  -----------------------------------------------------------------------------------------------------------------
}
