if krastorio.general.getSafeSettingValue("kr-containers") then
  data:extend({
    -- -- --
    -- MEDIUM CONTEINERS
    -- -- --
    {
      type = "recipe",
      name = "kr-medium-active-provider-container",
      energy_required = 1,
      enabled = false,
      ingredients = {
        { type = "item", name = "kr-medium-container", amount = 1 },
        { type = "item", name = "advanced-circuit", amount = 5 },
      },
      subgroup = "kr-logistics-2",
      order = "a[medium-active-provider-container]",
      results = { { type = "item", name = "kr-medium-active-provider-container", amount = 1 } },
      mod = "Krastorio2",
    },
    {
      type = "recipe",
      name = "kr-medium-buffer-container",
      energy_required = 1,
      enabled = false,
      ingredients = {
        { type = "item", name = "kr-medium-container", amount = 1 },
        { type = "item", name = "advanced-circuit", amount = 5 },
      },
      subgroup = "kr-logistics-2",
      order = "b[medium-buffer-container]",
      results = { { type = "item", name = "kr-medium-buffer-container", amount = 1 } },
      mod = "Krastorio2",
    },
    {
      type = "recipe",
      name = "kr-medium-container",
      energy_required = 2,
      enabled = false,
      ingredients = {
        { type = "item", name = "steel-chest", amount = 4 },
        { type = "item", name = "steel-beam", amount = 2 },
      },
      subgroup = "storage",
      order = "a[items]-d[medium-container]",
      results = { { type = "item", name = "kr-medium-container", amount = 1 } },
      mod = "Krastorio2",
    },
    {
      type = "recipe",
      name = "kr-medium-passive-provider-container",
      energy_required = 1,
      enabled = false,
      ingredients = {
        { type = "item", name = "kr-medium-container", amount = 1 },
        { type = "item", name = "advanced-circuit", amount = 5 },
      },
      subgroup = "kr-logistics-2",
      order = "c[medium-passive-provider-container]",
      results = { { type = "item", name = "kr-medium-passive-provider-container", amount = 1 } },
      mod = "Krastorio2",
    },
    {
      type = "recipe",
      name = "kr-medium-requester-container",
      energy_required = 1,
      enabled = false,
      ingredients = {
        { type = "item", name = "kr-medium-container", amount = 1 },
        { type = "item", name = "advanced-circuit", amount = 5 },
      },
      subgroup = "kr-logistics-2",
      order = "d[medium-requester-container]",
      results = { { type = "item", name = "kr-medium-requester-container", amount = 1 } },
      mod = "Krastorio2",
    },
    {
      type = "recipe",
      name = "kr-medium-storage-container",
      energy_required = 1,
      enabled = false,
      ingredients = {
        { type = "item", name = "kr-medium-container", amount = 1 },
        { type = "item", name = "advanced-circuit", amount = 5 },
      },
      subgroup = "kr-logistics-2",
      order = "e[medium-storage-container]",
      results = { { type = "item", name = "kr-medium-storage-container", amount = 1 } },
      mod = "Krastorio2",
    },
    -- -- --
    -- BIG CONTEINERS
    -- -- --
    {
      type = "recipe",
      name = "kr-big-active-provider-container",
      energy_required = 1,
      enabled = false,
      ingredients = {
        { type = "item", name = "kr-big-container", amount = 1 },
        { type = "item", name = "advanced-circuit", amount = 5 },
      },
      subgroup = "kr-logistics-3",
      order = "a[big-active-provider-container]",
      results = { { type = "item", name = "kr-big-active-provider-container", amount = 1 } },
      mod = "Krastorio2",
    },
    {
      type = "recipe",
      name = "kr-big-buffer-container",
      energy_required = 1,
      enabled = false,
      ingredients = {
        { type = "item", name = "kr-big-container", amount = 1 },
        { type = "item", name = "advanced-circuit", amount = 5 },
      },
      subgroup = "kr-logistics-3",
      order = "b[big-buffer-container]",
      results = { { type = "item", name = "kr-big-buffer-container", amount = 1 } },
      mod = "Krastorio2",
    },
    {
      type = "recipe",
      name = "kr-big-container",
      energy_required = 5,
      enabled = false,
      ingredients = {
        { type = "item", name = "kr-medium-container", amount = 4 },
        { type = "item", name = "steel-beam", amount = 10 },
      },
      subgroup = "storage",
      order = "a[items]-dz[big-container]",
      results = { { type = "item", name = "kr-big-container", amount = 1 } },
      mod = "Krastorio2",
    },
    {
      type = "recipe",
      name = "kr-big-passive-provider-container",
      energy_required = 1,
      enabled = false,
      ingredients = {
        { type = "item", name = "kr-big-container", amount = 1 },
        { type = "item", name = "advanced-circuit", amount = 5 },
      },
      subgroup = "kr-logistics-3",
      order = "c[big-passive-provider-container]",
      results = { { type = "item", name = "kr-big-passive-provider-container", amount = 1 } },
      mod = "Krastorio2",
    },
    {
      type = "recipe",
      name = "kr-big-requester-container",
      energy_required = 1,
      enabled = false,
      ingredients = {
        { type = "item", name = "kr-big-container", amount = 1 },
        { type = "item", name = "advanced-circuit", amount = 5 },
      },
      subgroup = "kr-logistics-3",
      order = "d[big-requester-container]",
      results = { { type = "item", name = "kr-big-requester-container", amount = 1 } },
      mod = "Krastorio2",
    },
    {
      type = "recipe",
      name = "kr-big-storage-container",
      energy_required = 1,
      enabled = false,
      ingredients = {
        { type = "item", name = "kr-big-container", amount = 1 },
        { type = "item", name = "advanced-circuit", amount = 5 },
      },
      subgroup = "kr-logistics-3",
      order = "e[big-storage-container]",
      results = { { type = "item", name = "kr-big-storage-container", amount = 1 } },
      mod = "Krastorio2",
    },
  })
end
