data:extend({
  {
    type = "recipe",
    name = "ai-core",
    enabled = false,
    category = "crafting-with-fluid",
    energy_required = 16,
    ingredients = {
      { type = "item", name = "processing-unit", amount = 2 },
      { type = "item", name = "imersite-crystal", amount = 2 },
      { type = "fluid", name = "nitric-acid", amount = 10 },
    },
    results = { { type = "item", name = "ai-core", amount = 2 } },
    allow_productivity = true,
  },
  {
    type = "recipe",
    name = "empty-antimatter-fuel-cell",
    category = "crafting-with-fluid",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { type = "fluid", name = "nitric-acid", amount = 50 },
      { type = "item", name = "energy-control-unit", amount = 10 },
      { type = "item", name = "imersium-plate", amount = 8 },
      { type = "item", name = "matter-stabilizer", amount = 2 },
    },
    results = { { type = "item", name = "empty-antimatter-fuel-cell", amount = 1 } },
    allow_as_intermediate = false,
    allow_productivity = true,
  },
  {
    type = "recipe",
    name = "landfill-2",
    localised_name = { "item-name.landfill" },
    localised_description = { "item-description.landfill" },
    icons = {
      { icon = "__base__/graphics/icons/landfill.png" },
      {
        icon = "__Krastorio2Assets__/icons/items/sand.png",
        scale = 0.26,
        shift = { 8, -8 },
      },
    },
    enabled = false,
    category = "crafting-with-fluid",
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "sand", amount = 50 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = { { type = "item", name = "landfill", amount = 1 } },
    allow_as_intermediate = false,
  },
  {
    type = "recipe",
    name = "restore-used-improved-pollution-filter",
    category = "crafting-with-fluid",
    icon = "__Krastorio2Assets__/icons/recipes/restore-used-improved-pollution-filter.png",
    icon_size = 128,
    subgroup = "intermediate-product",
    order = "w3-b[restore-used-pollution-filter]",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { type = "item", name = "used-improved-pollution-filter", amount = 1 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "item", name = "improved-pollution-filter", amount = 1 },
      { type = "fluid", name = "dirty-water", amount = 50 },
    },
  },
  {
    type = "recipe",
    name = "restore-used-pollution-filter",
    icon = "__Krastorio2Assets__/icons/recipes/restore-used-pollution-filter.png",
    icon_size = 128,
    subgroup = "intermediate-product",
    order = "w3-a[restore-used-pollution-filter]",
    enabled = false,
    category = "crafting-with-fluid",
    energy_required = 10,
    ingredients = {
      { type = "item", name = "used-pollution-filter", amount = 1 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "item", name = "pollution-filter", amount = 1 },
      { type = "fluid", name = "dirty-water", amount = 50 },
    },
  },
})
