data:extend({
  {
    type = "recipe",
    name = "sand",
    enabled = false,
    category = "crushing",
    energy_required = 1,
    ingredients = {
      { type = "item", name = "stone", amount = 3 },
    },
    results = {
      { type = "item", name = "sand", amount_min = 7, amount_max = 8 },
    },
    allow_as_intermediate = false,
    allow_intermediates = false,
    allow_productivity = true,
    always_show_made_in = true,
    always_show_products = true,
  },
  {
    type = "recipe",
    name = "imersite-powder",
    icon = "__Krastorio2Assets__/icons/items-with-variations/imersite-powder/imersite-powder.png",
    enabled = false,
    category = "crushing",
    energy_required = 3,
    ingredients = {
      { type = "item", name = "raw-imersite", amount = 3 },
    },
    results = {
      { type = "item", name = "imersite-powder", amount = 3 },
      { type = "item", name = "sand", amount = 3 },
    },
    main_product = "imersite-powder",
    allow_as_intermediate = false,
    allow_intermediates = false,
    allow_productivity = true,
    always_show_made_in = true,
    always_show_products = true,
  },
  {
    type = "recipe",
    name = "inserter-to-parts",
    factoriopedia_alternative = "inserter-parts",
    hide_from_player_crafting = true,
    enabled = true,
    category = "crushing",
    energy_required = 1,
    ingredients = {
      { type = "item", name = "inserter", amount = 1 },
    },
    results = {
      { type = "item", name = "inserter-parts", amount = 1 },
    },
    allow_as_intermediate = false,
    allow_intermediates = false,
    always_show_made_in = true,
    always_show_products = true,
  },
  {
    type = "recipe",
    name = "fast-inserter-to-parts",
    hide_from_player_crafting = true,
    enabled = true,
    category = "crushing",
    energy_required = 1,
    ingredients = {
      { type = "item", name = "fast-inserter", amount = 1 },
    },
    results = {
      { type = "item", name = "inserter-parts", amount = 1 },
    },
    allow_as_intermediate = false,
    allow_intermediates = false,
    always_show_made_in = true,
    always_show_products = true,
  },
  {
    type = "recipe",
    name = "long-handed-inserter-to-parts",
    hide_from_player_crafting = true,
    enabled = true,
    category = "crushing",
    energy_required = 1,
    ingredients = {
      { type = "item", name = "long-handed-inserter", amount = 1 },
    },
    results = {
      { type = "item", name = "inserter-parts", amount = 1 },
    },
    allow_as_intermediate = false,
    allow_intermediates = false,
    always_show_made_in = true,
    always_show_products = true,
  },
  {
    type = "recipe",
    name = "burner-inserter-to-parts",
    category = "crushing",
    hide_from_player_crafting = true,
    enabled = true,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "burner-inserter", amount = 1 },
    },
    results = {
      { type = "item", name = "inserter-parts", amount = 1 },
    },
    allow_as_intermediate = false,
    allow_intermediates = false,
    always_show_made_in = true,
    always_show_products = true,
  },
  {
    type = "recipe",
    name = "bulk-inserter-to-parts",
    icon = "__Krastorio2Assets__/icons/items-with-variations/electronic-components/electronic-components.png",
    subgroup = "intermediate-product",
    order = "e[ei-electronic-components]",
    hide_from_player_crafting = true,
    enabled = true,
    category = "crushing",
    energy_required = 1,
    ingredients = {
      { type = "item", name = "bulk-inserter", amount = 1 },
    },
    results = {
      { type = "item", name = "inserter-parts", amount = 1 },
      { type = "item", name = "electronic-components", amount = 2 },
    },
    allow_as_intermediate = false,
    allow_intermediates = false,
    always_show_made_in = true,
    always_show_products = true,
  },
  {
    type = "recipe",
    name = "superior-inserter-to-parts",
    localised_name = { "recipe-name.superior-inserter-to-parts" },
    icon = "__Krastorio2Assets__/icons/items-with-variations/electronic-components/electronic-components.png",
    subgroup = "intermediate-product",
    order = "e[ei-electronic-components]",
    hide_from_player_crafting = true,
    enabled = true,
    category = "crushing",
    energy_required = 1,
    ingredients = {
      { type = "item", name = "kr-superior-inserter", amount = 1 },
    },
    results = {
      { type = "item", name = "inserter-parts", amount = 1 },
      { type = "item", name = "electronic-components", amount = 4 },
      { type = "item", name = "imersite-powder", amount = 3 },
    },
    allow_as_intermediate = false,
    allow_intermediates = false,
    always_show_made_in = true,
    always_show_products = true,
  },
  {
    type = "recipe",
    name = "superior-long-inserter-to-parts",
    localised_name = { "recipe-name.superior-long-inserter-to-parts" },
    icon = "__Krastorio2Assets__/icons/items-with-variations/electronic-components/electronic-components.png",
    subgroup = "intermediate-product",
    order = "e[ei-electronic-components]",
    hide_from_player_crafting = true,
    enabled = true,
    category = "crushing",
    energy_required = 1,
    ingredients = {
      { type = "item", name = "kr-superior-long-inserter", amount = 1 },
    },
    results = {
      { type = "item", name = "inserter-parts", amount = 1 },
      { type = "item", name = "electronic-components", amount = 4 },
      { type = "item", name = "imersite-powder", amount = 6 },
    },
    allow_as_intermediate = false,
    allow_intermediates = false,
    always_show_made_in = true,
    always_show_products = true,
  },
  {
    type = "recipe",
    name = "imersite-crystal-to-dust",
    localised_name = { "recipe-name.imersite-crystal-to-dust" },
    icon = "__Krastorio2Assets__/icons/items-with-variations/imersite-powder/imersite-powder.png",
    subgroup = "intermediate-product",
    order = "e[ei-electronic-components]",
    hide_from_player_crafting = true,
    enabled = true,
    category = "crushing",
    energy_required = 1,
    ingredients = {
      { type = "item", name = "imersite-crystal", amount = 1 },
    },
    results = {
      { type = "item", name = "imersite-powder", amount = 3 },
    },
    allow_as_intermediate = false,
    allow_intermediates = false,
    always_show_made_in = true,
    always_show_products = true,
  },
})
