-- A RECIPE FOR STAY IN THIS FILE SHOULD !!NOT!! HAVE THE ATTRIBUTE category
return {
  {
    type = "recipe",
    name = "automation-core",
    energy_required = 2,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "iron-gear-wheel", amount = 4 },
      { type = "item", name = "iron-stick", amount = 4 },
      { type = "item", name = "copper-plate", amount = 6 },
    },
    results = { { type = "item", name = "automation-core", amount = 2 } },
  },
  {
    type = "recipe",
    name = "electronic-components",
    energy_required = 4,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "silicon", amount = 2 },
      { type = "item", name = "plastic-bar", amount = 2 },
      { type = "item", name = "glass", amount = 2 },
    },
    results = { { type = "item", name = "electronic-components", amount = 4 } },
  },
  {
    type = "recipe",
    name = "steel-gear-wheel",
    energy_required = 0.5,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "steel-plate", amount = 1 },
    },
    results = { { type = "item", name = "steel-gear-wheel", amount = 1 } },
  },
  {
    type = "recipe",
    name = "steel-beam",
    energy_required = 2,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "steel-plate", amount = 2 },
    },
    results = { { type = "item", name = "steel-beam", amount = 1 } },
  },
  {
    type = "recipe",
    name = "first-aid-kit",
    energy_required = 5,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "biomass", amount = 1 },
      { type = "item", name = "wood", amount = 1 },
      { type = "item", name = "iron-plate", amount = 1 },
    },
    results = { { type = "item", name = "first-aid-kit", amount = 1 } },
  },
  {
    type = "recipe",
    name = "landfill-2",
    localized_name = { "item-name.landfill" },
    localized_description = { "item-description.landfill" },
    icons = {
      { icon = "__base__/graphics/icons/landfill.png", icon_size = 64 },
      {
        icon = kr_items_with_variations_icons_path .. "sand/sand.png",
        icon_size = 64,
        scale = 0.26,
        shift = { 8, -8 },
      },
    },
    category = "crafting-with-fluid",
    enabled = false,
    allow_as_intermediate = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "sand", amount = 50 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = { { type = "item", name = "landfill", amount = 1 } },
  },
  {
    type = "recipe",
    name = "empty-dt-fuel",
    energy_required = 10,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "low-density-structure", amount = 2 },
      { type = "item", name = "rare-metals", amount = 1 },
    },
    results = { { type = "item", name = "empty-dt-fuel", amount = 1 } },
  },
  {
    type = "recipe",
    name = "kr-black-reinforced-plate",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "refined-concrete", amount = 20 },
      { type = "item", name = "steel-beam", amount = 5 },
    },
    results = { { type = "item", name = "kr-black-reinforced-plate", amount = 10 } },
  },
  {
    type = "recipe",
    name = "kr-white-reinforced-plate",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "refined-concrete", amount = 20 },
      { type = "item", name = "steel-beam", amount = 5 },
    },
    results = { { type = "item", name = "kr-white-reinforced-plate", amount = 10 } },
  },
  {
    type = "recipe",
    name = "ai-core",
    category = "crafting-with-fluid",
    energy_required = 16,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "processing-unit", amount = 2 },
      { type = "item", name = "imersite-crystal", amount = 2 },
      { type = "fluid", name = "nitric-acid", amount = 10 },
    },
    results = { { type = "item", name = "ai-core", amount = 2 } },
  },
  {
    type = "recipe",
    name = "pollution-filter",
    energy_required = 10,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "coal", amount = 2 },
      { type = "item", name = "steel-plate", amount = 2 },
      { type = "item", name = "plastic-bar", amount = 2 },
    },
    results = { { type = "item", name = "pollution-filter", amount = 1 } },
  },
  {
    type = "recipe",
    name = "restore-used-pollution-filter",
    category = "crafting-with-fluid",
    icon = kr_recipes_icons_path .. "restore-used-pollution-filter.png",
    icon_size = 128,
    energy_required = 10,
    enabled = false,
    ingredients = {
      { type = "item", name = "used-pollution-filter", amount = 1 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "item", name = "pollution-filter", amount = 1 },
      { type = "fluid", name = "dirty-water", amount = 50 },
    },
    subgroup = "intermediate-product",
    order = "w3-a[restore-used-pollution-filter]",
  },
  {
    type = "recipe",
    name = "improved-pollution-filter",
    energy_required = 10,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "pollution-filter", amount = 1 },
      { type = "item", name = "biomass", amount = 1 },
      { type = "item", name = "imersite-powder", amount = 1 },
    },
    results = { { type = "item", name = "improved-pollution-filter", amount = 1 } },
  },
  {
    type = "recipe",
    name = "restore-used-improved-pollution-filter",
    category = "crafting-with-fluid",
    icon = kr_recipes_icons_path .. "restore-used-improved-pollution-filter.png",
    icon_size = 128,
    energy_required = 10,
    enabled = false,
    ingredients = {
      { type = "item", name = "used-improved-pollution-filter", amount = 1 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "item", name = "improved-pollution-filter", amount = 1 },
      { type = "fluid", name = "dirty-water", amount = 50 },
    },
    subgroup = "intermediate-product",
    order = "w3-b[restore-used-pollution-filter]",
  },
  ---
  {
    type = "recipe",
    name = "imersium-gear-wheel",
    energy_required = 0.5,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "imersium-plate", amount = 1 },
    },
    results = { { type = "item", name = "imersium-gear-wheel", amount = 1 } },
  },
  {
    type = "recipe",
    name = "imersium-beam",
    energy_required = 3,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "imersium-plate", amount = 2 },
    },
    results = { { type = "item", name = "imersium-beam", amount = 1 } },
  },
  {
    type = "recipe",
    name = "impulse-rifle",
    energy_required = 30,
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-plate", amount = 5 },
      { type = "item", name = "low-density-structure", amount = 5 },
      { type = "item", name = "imersite-crystal", amount = 1 },
      { type = "item", name = "steel-gear-wheel", amount = 1 },
    },
    results = { { type = "item", name = "impulse-rifle", amount = 1 } },
  },
  {
    type = "recipe",
    name = "heavy-rocket-launcher",
    energy_required = 60,
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-plate", amount = 5 },
      { type = "item", name = "low-density-structure", amount = 5 },
      { type = "item", name = "steel-gear-wheel", amount = 1 },
      { type = "item", name = "processing-unit", amount = 1 },
    },
    results = { { type = "item", name = "heavy-rocket-launcher", amount = 1 } },
  },
  {
    type = "recipe",
    name = "impulse-rifle-ammo",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "lithium-sulfur-battery", amount = 1 },
      { type = "item", name = "imersite-crystal", amount = 3 },
      { type = "item", name = "plastic-bar", amount = 1 },
    },
    results = { { type = "item", name = "impulse-rifle-ammo", amount = 1 } },
  },
  {
    type = "recipe",
    name = "imersite-rounds-magazine",
    enabled = false,
    energy_required = 20,
    ingredients = {
      { type = "item", name = "imersite-crystal", amount = 2 },
      { type = "item", name = "piercing-rounds-magazine", amount = 1 },
    },
    results = { { type = "item", name = "imersite-rounds-magazine", amount = 1 } },
  },
  {
    type = "recipe",
    name = "heavy-rocket",
    energy_required = 10,
    enabled = false,
    ingredients = {
      { type = "item", name = "explosives", amount = 10 },
      { type = "item", name = "steel-plate", amount = 5 },
      { type = "item", name = "rocket-fuel", amount = 10 },
      { type = "item", name = "plastic-bar", amount = 5 },
      { type = "item", name = "processing-unit", amount = 1 },
    },
    results = { { type = "item", name = "heavy-rocket", amount = 1 } },
  },
  {
    type = "recipe",
    name = "energy-control-unit",
    enabled = false,
    allow_productivity = true,
    energy_required = 10,
    ingredients = {
      { type = "item", name = "low-density-structure", amount = 6 },
      { type = "item", name = "imersite-crystal", amount = 3 },
      { type = "item", name = "electronic-components", amount = 9 },
      { type = "item", name = "lithium-sulfur-battery", amount = 3 },
    },
    results = { { type = "item", name = "energy-control-unit", amount = 1 } },
  },
  {
    type = "recipe",
    name = "matter-stabilizer",
    enabled = false,
    allow_as_intermediate = false,
    allow_productivity = true,
    energy_required = 5,
    ingredients = {
      { type = "item", name = "imersium-plate", amount = 6 },
      { type = "item", name = "energy-control-unit", amount = 3 },
      { type = "item", name = "processing-unit", amount = 3 },
    },
    results = { { type = "item", name = "matter-stabilizer", amount = 1 } },
  },
  {
    type = "recipe",
    name = "empty-antimatter-fuel-cell",
    category = "crafting-with-fluid",
    enabled = false,
    allow_as_intermediate = false,
    allow_productivity = true,
    energy_required = 10,
    ingredients = {
      { type = "fluid", name = "nitric-acid", amount = 50 },
      { type = "item", name = "energy-control-unit", amount = 10 },
      { type = "item", name = "imersium-plate", amount = 8 },
      { type = "item", name = "matter-stabilizer", amount = 2 },
    },
    results = { { type = "item", name = "empty-antimatter-fuel-cell", amount = 1 } },
  },
  {
    type = "recipe",
    name = "charged-antimatter-fuel-cell",
    category = "matter-deconversion",
    enabled = false,
    allow_as_intermediate = false,
    energy_required = 5,
    ingredients = {
      { type = "fluid", name = "matter", amount = 1000 },
      { type = "item", name = "empty-antimatter-fuel-cell", amount = 1 },
    },
    results = { { type = "item", name = "charged-antimatter-fuel-cell", amount = 1 } },
  },
  {
    type = "recipe",
    name = "basic-railgun-shell",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { type = "item", name = "steel-plate", amount = 5 },
      { type = "item", name = "advanced-circuit", amount = 1 },
    },
    results = { { type = "item", name = "basic-railgun-shell", amount = 1 } },
  },
  {
    type = "recipe",
    name = "explosion-railgun-shell",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { type = "item", name = "basic-railgun-shell", amount = 1 },
      { type = "item", name = "explosives", amount = 3 },
    },
    results = { { type = "item", name = "explosion-railgun-shell", amount = 1 } },
  },
  {
    type = "recipe",
    name = "explosive-turret-rocket",
    enabled = false,
    energy_required = 20,
    ingredients = {
      { type = "item", name = "rocket-fuel", amount = 10 },
      { type = "item", name = "rocket-control-unit", amount = 1 },
      { type = "item", name = "steel-plate", amount = 5 },
      { type = "item", name = "explosives", amount = 5 },
    },
    results = { { type = "item", name = "explosive-turret-rocket", amount = 1 } },
  },
  {
    type = "recipe",
    name = "nuclear-turret-rocket",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "explosive-turret-rocket", amount = 1 },
      { type = "item", name = "steel-plate", amount = 5 },
      { type = "item", name = "uranium-235", amount = 10 },
      { type = "item", name = "rocket-control-unit", amount = 1 },
    },
    results = { { type = "item", name = "nuclear-turret-rocket", amount = 1 } },
  },
  {
    type = "recipe",
    name = "antimatter-turret-rocket",
    enabled = false,
    energy_required = 5,
    ingredients = {
      { type = "item", name = "imersium-plate", amount = 1 },
      { type = "item", name = "explosive-turret-rocket", amount = 1 },
      { type = "item", name = "charged-antimatter-fuel-cell", amount = 1 },
      { type = "item", name = "processing-unit", amount = 1 },
    },
    results = { { type = "item", name = "antimatter-turret-rocket", amount = 1 } },
  },
  {
    type = "recipe",
    name = "antimatter-artillery-shell",
    enabled = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "imersium-plate", amount = 1 },
      { type = "item", name = "artillery-shell", amount = 1 },
      { type = "item", name = "charged-antimatter-fuel-cell", amount = 1 },
      { type = "item", name = "processing-unit", amount = 1 },
    },
    results = { { type = "item", name = "antimatter-artillery-shell", amount = 1 } },
  },
  {
    type = "recipe",
    name = "antimatter-rocket",
    enabled = false,
    energy_required = 10,
    ingredients = {
      { type = "item", name = "imersium-plate", amount = 2 },
      { type = "item", name = "heavy-rocket", amount = 1 },
      { type = "item", name = "charged-antimatter-fuel-cell", amount = 3 },
      { type = "item", name = "processing-unit", amount = 1 },
    },
    results = { { type = "item", name = "antimatter-rocket", amount = 1 } },
  },
  {
    type = "recipe",
    name = "antimatter-railgun-shell",
    enabled = false,
    energy_required = 5,
    ingredients = {
      { type = "item", name = "imersium-plate", amount = 1 },
      { type = "item", name = "basic-railgun-shell", amount = 1 },
      { type = "item", name = "charged-antimatter-fuel-cell", amount = 1 },
      { type = "item", name = "processing-unit", amount = 1 },
    },
    results = { { type = "item", name = "antimatter-railgun-shell", amount = 1 } },
  },
  {
    type = "recipe",
    name = "nuclear-artillery-shell",
    enabled = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "rocket-control-unit", amount = 10 },
      { type = "item", name = "steel-plate", amount = 10 },
      { type = "item", name = "artillery-shell", amount = 1 },
      { type = "item", name = "uranium-235", amount = 10 },
    },
    results = { { type = "item", name = "nuclear-artillery-shell", amount = 1 } },
  },
  {
    type = "recipe",
    name = "gps-satellite",
    enabled = false,
    energy_required = 5,
    ingredients = {
      { type = "item", name = "satellite", amount = 1 },
      { type = "item", name = "rocket-control-unit", amount = 1 },
      { type = "item", name = "ai-core", amount = 4 },
    },
    results = { { type = "item", name = "gps-satellite", amount = 1 } },
  },
}
