-- A RECIPE FOR STAY IN THIS FILE SHOULD HAVE PRODUCTS THAT IS ONLY TOOLS

return {
  {
    type = "recipe",
    name = "blank-tech-card",
    energy_required = 2,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "iron-plate", amount = 2 },
      { type = "item", name = "copper-cable", amount = 2 },
    },
    results = { { type = "item", name = "blank-tech-card", amount = 5 } },
  },
  {
    type = "recipe",
    name = "biters-research-data",
    energy_required = 40,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "biomass", amount = 10 },
      { type = "item", name = "coke", amount = 5 },
      { type = "item", name = "steel-plate", amount = 5 },
    },
    results = { { type = "item", name = "biters-research-data", amount = 5 } },
  },
  {
    type = "recipe",
    name = "basic-tech-card",
    energy_required = 20,
    enabled = true,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "wood", amount = 5 },
      { type = "item", name = "copper-cable", amount = 5 },
    },
    results = { { type = "item", name = "basic-tech-card", amount = 5 } },
  },
  {
    type = "recipe",
    name = kr_optimization_tech_card_name,
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "blank-tech-card", amount = 10 },
      { type = "item", name = "space-research-data", amount = 5 },
    },
    results = { { type = "item", name = kr_optimization_tech_card_name, amount = 5 } },
  },
  {
    type = "recipe",
    name = "matter-research-data",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "imersite-crystal", amount = 5 },
      { type = "item", name = "rare-metals", amount = 5 },
      { type = "item", name = "lithium", amount = 5 },
      { type = "item", name = "plastic-bar", amount = 5 },
    },
    results = { { type = "item", name = "matter-research-data", amount = 5 } },
  },
  {
    type = "recipe",
    name = "matter-tech-card",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "blank-tech-card", amount = 15 },
      { type = "item", name = "matter-research-data", amount = 5 },
      { type = "item", name = "processing-unit", amount = 5 },
    },
    results = { { type = "item", name = "matter-tech-card", amount = 5 } },
  },
  {
    type = "recipe",
    name = "advanced-tech-card",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "blank-tech-card", amount = 15 },
      { type = "item", name = "imersium-gear-wheel", amount = 20 },
      { type = "item", name = "lithium-sulfur-battery", amount = 10 },
      { type = "item", name = "electric-engine-unit", amount = 5 },
    },
    results = { { type = "item", name = "advanced-tech-card", amount = 5 } },
  },
  {
    type = "recipe",
    name = "singularity-tech-card",
    category = "t3-tech-cards",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "blank-tech-card", amount = 15 },
      { type = "item", name = "charged-matter-stabilizer", amount = 5 },
      { type = "item", name = "ai-core", amount = 5 },
    },
    results = { { type = "item", name = "singularity-tech-card", amount = 5 } },
  },
}
