require(kr_categories_path .. "item-subgroups")
require(kr_categories_path .. "fuel-categories")
require(kr_categories_path .. "recipe-categories")
require(kr_categories_path .. "resource-categories")
require(kr_categories_path .. "equipment-categories")
require(kr_categories_path .. "ammos-categories")
