require("prototypes.categories.item-subgroups")
require("prototypes.categories.fuel-categories")
require("prototypes.categories.recipe-categories")
require("prototypes.categories.resource-categories")
require("prototypes.categories.equipment-categories")
require("prototypes.categories.ammos-categories")
