data:extend({
  {
    type = "item-group",
    name = "smelting-crafting",
    order = "m4",
    icon = "__Krastorio2Assets__/icons/item-groups/smelting-crafting.png",
    icon_size = 64,
  },
  {
    type = "item-subgroup",
    name = "crash-site",
    group = "other",
    order = "zz",
  },
  {
    type = "item-subgroup",
    name = "kr-decorations-1",
    group = "environment",
    order = "d1",
  },
  {
    type = "item-subgroup",
    name = "kr-decorations-2",
    group = "environment",
    order = "d2",
  },
  {
    type = "item-subgroup",
    name = "kr-logistics-1",
    group = "logistics",
    order = "a1",
  },
  {
    type = "item-subgroup",
    name = "kr-logistics-2",
    group = "logistics",
    order = "a2",
  },
  {
    type = "item-subgroup",
    name = "kr-logistics-3",
    group = "logistics",
    order = "a3",
  },
  {
    type = "item-subgroup",
    name = "kr-logistics-4", -- for compatibility
    group = "logistics",
    order = "a4",
  },
  {
    type = "item-subgroup",
    name = "kr-special-signals",
    group = "signals",
    order = "z1",
  },
  {
    type = "item-subgroup",
    name = "kr-special-signals-2",
    group = "signals",
    order = "z2",
  },
  {
    type = "item-subgroup",
    name = "kr-void",
    group = "other",
    order = "zzz",
  },
  {
    type = "item-subgroup",
    name = "matter-conversion",
    group = "intermediate-products",
    order = "m1",
  },
  {
    type = "item-subgroup",
    name = "matter-deconversion",
    group = "intermediate-products",
    order = "m2",
  },
  {
    type = "item-subgroup",
    name = "matter-items",
    group = "intermediate-products",
    order = "m3",
  },
  {
    type = "item-subgroup",
    name = "radars",
    group = "combat",
    order = "g4",
  },
  {
    type = "item-subgroup",
    name = "railgun-turret",
    group = "combat",
    order = "g2",
  },
  {
    type = "item-subgroup",
    name = "rocket-turret",
    group = "combat",
    order = "g3",
  },
  {
    type = "item-subgroup",
    name = "smelting-crafting",
    group = "smelting-crafting",
    order = "m4",
  },
  {
    type = "item-subgroup",
    name = "vanilla-turrets",
    group = "combat",
    order = "g1",
  },
})
