data:extend({
  {
    type = "equipment-grid",
    name = "kr-car-grid",
    width = 6,
    height = 6,
    equipment_categories = {
      "universal-equipment",
      "vehicle-robot-interaction-equipment",
      "vehicle-equipment",
      "vehicle-motor",
    },
  },
  {
    type = "equipment-grid",
    name = "kr-locomotive-grid",
    width = 12,
    height = 12,
    equipment_categories = { "universal-equipment", "vehicle-equipment", "vehicle-motor" },
  },
  {
    type = "equipment-grid",
    name = "kr-spidertron-equipment-grid",
    width = 10,
    height = 6,
    equipment_categories = {
      "universal-equipment",
      "vehicle-robot-interaction-equipment",
      "vehicle-equipment",
      "vehicle-motor",
    },
  },
  {
    type = "equipment-grid",
    name = "kr-tank-grid",
    width = 6,
    height = 11,
    equipment_categories = {
      "universal-equipment",
      "vehicle-robot-interaction-equipment",
      "vehicle-equipment",
      "vehicle-motor",
    },
  },
  {
    type = "equipment-grid",
    name = "kr-tank-grid-2",
    width = 12,
    height = 15,
    equipment_categories = {
      "universal-equipment",
      "vehicle-robot-interaction-equipment",
      "vehicle-equipment",
      "vehicle-motor",
    },
  },
  {
    type = "equipment-grid",
    name = "kr-wagons-grid",
    width = 6,
    height = 16,
    equipment_categories = {
      "universal-equipment",
      "vehicle-equipment",
      "vehicle-robot-interaction-equipment",
    },
  },
  {
    type = "equipment-grid",
    name = "mk3-armor-grid",
    width = 10,
    height = 10,
    equipment_categories = { "armor", "universal-equipment" },
  },
  {
    type = "equipment-grid",
    name = "mk4-armor-grid",
    width = 12,
    height = 12,
    equipment_categories = { "armor", "universal-equipment" },
  },
})
