data:extend({
  {
    type = "fluid",
    name = "ammonia",
    icon = "__Krastorio2Assets__/icons/fluids/ammonia.png",
    order = "ya05[ammonia]",
    subgroup = "fluid",
    default_temperature = 25,
    gas_temperature = 25,
    max_temperature = 100,
    base_color = { r = 0.25, g = 0.25, b = 0.45 },
    flow_color = { r = 0.25, g = 0.25, b = 0.45 },
    base_flow_rate = 100,
    auto_barrel = true,
  },
  {
    type = "fluid",
    name = "biomethanol",
    icon = "__Krastorio2Assets__/icons/fluids/biomethanol.png",
    order = "ya08[biomethanol]",
    subgroup = "fluid",
    default_temperature = 25,
    gas_temperature = 30,
    max_temperature = 100,
    base_color = { r = 0.25, g = 0.53, b = 0.15 },
    flow_color = { r = 0.27, g = 0.53, b = 0.12 },
    fuel_value = "750kJ",
    emissions_multiplier = 0.8,
    base_flow_rate = 100,
    auto_barrel = true,
  },
  {
    type = "fluid",
    name = "chlorine",
    icon = "__Krastorio2Assets__/icons/fluids/chlorine.png",
    order = "ya02[chlorine]",
    subgroup = "fluid",
    default_temperature = 25,
    gas_temperature = 25,
    max_temperature = 100,
    base_color = { r = 0.30, g = 0.60, b = 0.1 },
    flow_color = { r = 0.30, g = 0.60, b = 0.1 },
    base_flow_rate = 100,
    auto_barrel = true,
  },
  {
    type = "fluid",
    name = "dirty-water",
    icon = "__Krastorio2Assets__/icons/fluids/dirty-water.png",
    order = "ya03[dirty-water]",
    subgroup = "fluid",
    default_temperature = 25,
    max_temperature = 100,
    base_color = { r = 0.65, g = 0.50, b = 0.20 },
    flow_color = { r = 0.65, g = 0.50, b = 0.20 },
    base_flow_rate = 100,
    auto_barrel = true,
  },
  {
    type = "fluid",
    name = "heavy-water",
    icon = "__Krastorio2Assets__/icons/fluids/heavy-water.png",
    order = "ya09[heavy-water]",
    subgroup = "fluid",
    default_temperature = 25,
    max_temperature = 100,
    base_color = { r = 0.2, g = 0.3, b = 0.32 },
    flow_color = { r = 0.5, g = 0.9, b = 0.6 },
    base_flow_rate = 100,
    auto_barrel = true,
  },
  {
    type = "fluid",
    name = "hydrogen",
    icon = "__Krastorio2Assets__/icons/fluids/hydrogen.png",
    order = "ya01[hydrogen]",
    subgroup = "fluid",
    default_temperature = 25,
    gas_temperature = 25,
    max_temperature = 100,
    base_color = { r = 0.50, g = 0.50, b = 0.50 },
    flow_color = { r = 0.50, g = 0.50, b = 0.50 },
    base_flow_rate = 100,
    auto_barrel = true,
  },
  {
    type = "fluid",
    name = "hydrogen-chloride",
    icon = "__Krastorio2Assets__/icons/fluids/hydrogen-chloride.png",
    order = "ya07[hydrogen-chloride]",
    subgroup = "fluid",
    default_temperature = 25,
    gas_temperature = 25,
    max_temperature = 100,
    base_color = { r = 0.50, g = 0.75, b = 0.30 },
    flow_color = { r = 0.50, g = 0.75, b = 0.30 },
    base_flow_rate = 100,
    auto_barrel = true,
  },
  {
    type = "fluid",
    name = "matter",
    icon = "__Krastorio2Assets__/icons/fluids/matter.png",
    order = "ym00[k-matter]",
    subgroup = "fluid",
    default_temperature = 25,
    max_temperature = 1000000,
    base_color = { r = 0.1, g = 0.9, b = 0.8 },
    flow_color = { r = 1, g = 1, b = 1 },
    base_flow_rate = 100,
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "mineral-water",
    icon = "__Krastorio2Assets__/icons/fluids/mineral-water.png",
    order = "ya01[mineral-water]",
    subgroup = "fluid",
    default_temperature = 25,
    max_temperature = 100,
    base_color = { r = 0.15, g = 0.1, b = 0.4 },
    flow_color = { r = 0.5, g = 0.5, b = 0.75 },
    base_flow_rate = 100,
    auto_barrel = true,
  },
  {
    type = "fluid",
    name = "nitric-acid",
    icon = "__Krastorio2Assets__/icons/fluids/nitric-acid.png",
    order = "ya06[nitric-acid]",
    subgroup = "fluid",
    default_temperature = 25,
    gas_temperature = 25,
    max_temperature = 100,
    base_color = { r = 0.752, g = 0.215, b = 0.337, a = 1.0 },
    flow_color = { r = 0.752, g = 0.215, b = 0.337, a = 0.8 },
    base_flow_rate = 100,
    auto_barrel = true,
  },
  {
    type = "fluid",
    name = "nitrogen",
    icon = "__Krastorio2Assets__/icons/fluids/nitrogen.png",
    order = "ya04[nitrogen]",
    subgroup = "fluid",
    default_temperature = 25,
    gas_temperature = 25,
    max_temperature = 100,
    base_color = { r = 0.05, g = 0.10, b = 0.50 },
    flow_color = { r = 0.05, g = 0.10, b = 0.50 },
    base_flow_rate = 100,
    auto_barrel = true,
  },
  {
    type = "fluid",
    name = "oxygen",
    icon = "__Krastorio2Assets__/icons/fluids/oxygen.png",
    order = "ya03[oxygen]",
    subgroup = "fluid",
    default_temperature = 25,
    gas_temperature = 25,
    max_temperature = 100,
    base_color = { r = 0.75, g = 0.40, b = 0.40 },
    flow_color = { r = 0.80, g = 0.60, b = 0.60 },
    base_flow_rate = 100,
    auto_barrel = true,
  },
})
