data:extend({
  {
    type = "explosion",
    name = "kr-laser-explosion-gunshot",
    flags = { "not-on-map" },
    hidden = true,
    subgroup = "explosions",
    animations = {
      {
        filename = "__Krastorio2Assets__/explosions/laser_gunshot.png",
        priority = "extra-high",
        draw_as_glow = true,
        width = 51,
        height = 57,
        frame_count = 2,
        animation_speed = 1.3,
        shift = { 0, 0 },
      },
      {
        filename = "__Krastorio2Assets__/explosions/laser_gunshot.png",
        priority = "high",
        draw_as_glow = true,
        blend_mode = "additive",
        width = 51,
        height = 57,
        frame_count = 2,
        animation_speed = 1.3,
        shift = { 0, 0 },
      },
      {
        filename = "__Krastorio2Assets__/explosions/laser_gunshot.png",
        priority = "medium",
        width = 51,
        height = 57,
        frame_count = 2,
        animation_speed = 1.3,
        shift = { 0, 0 },
      },
    },
    rotate = true,
    smoke = "kr-laser-explosion-gunshot-smoke-fast",
    smoke_count = 2,
    smoke_slow_down_factor = 0.25,
  },
})
