data:extend({
  {
    type = "corpse",
    name = "kr-antimatter-reactor-remnant",
    localised_name = { "remnant-name", { "entity-name.kr-antimatter-reactor" } },
    icon = "__Krastorio2Assets__/icons/entities/antimatter-reactor.png",
    flags = { "placeable-neutral", "building-direction-8-way", "not-on-map" },
    hidden_in_factoriopedia = true,
    subgroup = "remnants",
    order = "z[remnants]-a[generic]-b[medium]",
    selection_box = { { -4.5, -4.5 }, { 4.5, 4.5 } },
    tile_width = 9,
    tile_height = 9,
    selectable_in_game = false,
    time_before_removed = 20 * minute,
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = make_rotated_animation_variations_from_sheet(1, {
      filename = "__Krastorio2Assets__/remnants/antimatter-reactor-remnant/antimatter-reactor-remnant.png",
      line_length = 1,
      width = 600,
      height = 600,
      frame_count = 1,
      direction_count = 1,
      scale = 0.55,
    }),
  },
})
