data:extend({
  {
    type = "corpse",
    name = "kr-superior-inserter-remnants",
    localised_name = { "remnant-name", { "entity-name.kr-superior-inserter" } },
    icon = "__Krastorio2Assets__/icons/entities/superior-inserter.png",
    flags = { "placeable-neutral", "not-on-map" },
    hidden_in_factoriopedia = true,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    tile_width = 1,
    tile_height = 1,
    selectable_in_game = false,
    time_before_removed = 15 * minute,
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = make_rotated_animation_variations_from_sheet(3, {
      filename = "__Krastorio2Assets__/remnants/superior-inserter-remnant/superior-inserter-remnant.png",
      line_length = 1,
      width = 102,
      height = 80,
      frame_count = 1,
      variation_count = 1,
      axially_symmetrical = false,
      direction_count = 1,
      shift = util.by_pixel(0.5, 4.5),
      scale = 0.5,
    }),
  },
})
