require("compatibility-scripts/data-updates/aai-vehicles/aai-vehicles-chaingunner")
require("compatibility-scripts/data-updates/aai-vehicles/aai-vehicles-flame-tank")
require("compatibility-scripts/data-updates/aai-vehicles/aai-vehicles-flame-tumbler")
require("compatibility-scripts/data-updates/aai-vehicles/aai-vehicles-hauler")
require("compatibility-scripts/data-updates/aai-vehicles/aai-vehicles-laser-tank")
require("compatibility-scripts/data-updates/aai-vehicles/aai-vehicles-miner")
require("compatibility-scripts/data-updates/aai-vehicles/aai-vehicles-warden")
